/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaasg.login;

import HR.HR_interface;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import com.formdev.flatlaf.*;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import departmentmanager.DepartmentMng;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javaasg.UserMng;
import javaasg.adduserv;
import javaasg.forgotpssw;
import raven.popup.GlassPanePopup;
import raven.popup.DefaultOption;
import raven.popup.component.SimplePopupBorder;
import raven.toast.Notifications;
/**
 *
 * @author acer
 */
public class logintest extends javax.swing.JFrame {

   
    
    public logintest() {
        initComponents();
        hideeye.setVisible(false);
        showeye.setVisible(true);
        
        raven.popup.GlassPanePopup.install(this);
        raven.toast.Notifications.getInstance().setJFrame(this);
        
    }
    
     public static String[] adminprofiled; //define the array name

    public static void setuserDetails(String[] adminDetails) { //store the admindetail string inside var 
        adminprofiled = adminDetails;
    }

    public static String[] getuserDetails() { //return whatever store
        return adminprofiled;
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        text2 = new designcomponent.text();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel3 = new javax.swing.JLabel();
        password1 = new designcomponent.password();
        buttonlogin2 = new designcomponent.buttonlogin();
        hideeye = new javax.swing.JLabel();
        showeye = new javax.swing.JLabel();
        forgot = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 251, 244));

        jPanel1.setBackground(new java.awt.Color(242, 237, 229));
        jPanel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(242, 237, 229));
        jPanel2.setOpaque(false);

        text2.setBackground(new java.awt.Color(255, 251, 244));
        text2.setForeground(new java.awt.Color(51, 51, 51));
        text2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        text2.setLineColor(new java.awt.Color(158, 137, 105));

        jLabel2.setBackground(new java.awt.Color(242, 237, 229));
        jLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 56)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaasg/image/newlogo lightback.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        password1.setBackground(new java.awt.Color(255, 251, 244));
        password1.setForeground(new java.awt.Color(51, 51, 51));
        password1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        password1.setLineColor(new java.awt.Color(80, 68, 52));
        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });

        buttonlogin2.setBorder(null);
        buttonlogin2.setForeground(new java.awt.Color(223, 208, 185));
        buttonlogin2.setText("LOGIN");
        buttonlogin2.setColor(new java.awt.Color(93, 12, 29));
        buttonlogin2.setColorClick(new java.awt.Color(158, 137, 105));
        buttonlogin2.setColorOver(new java.awt.Color(147, 21, 48));
        buttonlogin2.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        buttonlogin2.setIconTextGap(5);
        buttonlogin2.setRadius(45);
        buttonlogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlogin2ActionPerformed(evt);
            }
        });

        hideeye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaasg/image/eye_hide_psw.png"))); // NOI18N
        hideeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideeyeMouseClicked(evt);
            }
        });

        showeye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaasg/image/eye_psw.png"))); // NOI18N
        showeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showeyeMouseClicked(evt);
            }
        });

        forgot.setForeground(new java.awt.Color(36, 72, 107));
        forgot.setText("Forgot Password?");
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonlogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgot))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hideeye, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showeye, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hideeye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showeye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(forgot)
                .addGap(18, 18, 18)
                .addComponent(buttonlogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(93, 12, 29));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaasg/image/newlogo.png"))); // NOI18N
        jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int chance = 0;
    
    private void buttonlogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlogin2ActionPerformed
        // TODO add your handling code here:
        String username = text2.getText().trim();
        String password = new String(password1.getPassword());
        
        Login login = new Login();
        
            
        //check username
        if (Login.validate(username, password)) {
            String role = login.checkrole(username);
            String status = login.checkstatus(username);
            
            //check status lock or unlock
            if(status.equalsIgnoreCase("Locked")){
                jLabel3.setText("Account Locked, please contact the Admin.");
            } else {
                //check role to switch frame
                if (role != null){
                    if (role.equalsIgnoreCase("System Administrator")){
                        String[] adminp = getuserDetails();
                        setuserDetails(adminp);
                        UserMng sysad = new UserMng();
                        sysad.setVisible(true);
                        this.dispose();
                        
                        
                    } else if (role.equalsIgnoreCase("Human Resource Officer")){
                        String[] adminp = getuserDetails();
                        setuserDetails(adminp);
                        HR_interface hr = new HR_interface();
                        hr.setVisible(true);
                        this.dispose();
                        
                        
                    } else if (role.equalsIgnoreCase("Department Manager")){
                        String[] adminp = getuserDetails();
                        setuserDetails(adminp);
                        DepartmentMng depart = new DepartmentMng();
                        depart.setVisible(true);
                        this.dispose();
                        
                        
                    }
                    
                }




                jLabel3.setText("Login Success!");
            }
        } else {
            chance++;
            if (chance >= 3){
                Login.lockacc(username);
                jLabel3.setText("Account Locked. Please contact the admin.");
                text2.setEditable(false);
                password1.setEditable(false);
                buttonlogin2.setEnabled(false);
            } else{
            jLabel3.setText("Invalid username or password");
            }
            
        }

    }//GEN-LAST:event_buttonlogin2ActionPerformed

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("");
    }//GEN-LAST:event_password1ActionPerformed

    //show password
    private boolean showpass = false;
    
    private void showeyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showeyeMouseClicked
        // TODO add your handling code here:
        showpass = true;
            password1.setEchoChar((char)0);
            showeye.setVisible(false);
            hideeye.setVisible(true);
        
    }//GEN-LAST:event_showeyeMouseClicked

    private void hideeyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideeyeMouseClicked
        // TODO add your handling code here:
        showpass = false;
        password1.setEchoChar('*');
        showeye.setVisible(true);
        hideeye.setVisible(false);

    }//GEN-LAST:event_hideeyeMouseClicked

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked
        //forgot password panel
        forgotpssw fpssw = new forgotpssw();
        DefaultOption option=new DefaultOption(){
           //@Override
           public boolean closeWhenClickedOutside(){
               return true;
           }
       };
       String actions[]=new String []{"Cancel","Save"};
       GlassPanePopup.showPopup(new SimplePopupBorder(fpssw, "Change Password", actions, (pc, i) -> {
            if (i == 1) {
                // save click
                try {
                    //check empty
                    boolean valid = fpssw.emptyfp();
                    if(!valid){
                        Notifications.getInstance().show(Notifications.Type.ERROR, "Field cannot be empty");
                        return;
                    }
                    
                   
                    //confirm password
                    String txtnewps = fpssw.getnps();
                    String txtconps = fpssw.getcps();
                    boolean confirmps = fpssw.matchpw(txtnewps,txtconps);
                    if(!confirmps){
                        Notifications.getInstance().show(Notifications.Type.ERROR, "Password not same");
                        return;
                    }
                    
                    //check ic if user exist
                    String txtNRIC = fpssw.getIC();
                    if(!txtNRIC.isEmpty()){
                        if (!adduserv.validatefp(txtNRIC)){
                        Notifications.getInstance().show(Notifications.Type.ERROR, "Employee does not exist");
                        return;
                        }}
                    
                    boolean pssave = fpssw.savepssw();
                    if (!pssave){
                        Notifications.getInstance().show(Notifications.Type.ERROR, "error in saving");
                        return;
                    }
                    
                    
                    fpssw.savepssw();
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, "New Password Saved");
                        
                    pc.closePopup();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                pc.closePopup();
            }
        }), option);
    }//GEN-LAST:event_forgotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logintest().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private designcomponent.buttonlogin buttonlogin2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel forgot;
    private javax.swing.JLabel hideeye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private designcomponent.password password1;
    private javax.swing.JLabel showeye;
    private designcomponent.text text2;
    // End of variables declaration//GEN-END:variables
}
