/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaasg;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javaasg.login.logintest;
import static javaasg.login.logintest.adminprofiled;

/**
 *
 * @author acer
 */
public class Changepssw extends javax.swing.JPanel {

    
    public Changepssw() {
        initComponents();
    }

    public boolean changep(String username) {
            
        String file="C:\\Users\\acer\\Documents\\NetBeansProjects\\JavaAsg\\src\\csv\\Employees_DetailsCSV.csv";
        
        String oldp = oldpssw.getText();
        String newp = newpssw.getText();
        String cp = confirmpssw.getText();
       
        
        
        List<String[]> csvData = new ArrayList<>();
        boolean isupdated=false;
        
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] field = line.split(",");
                if (field[3].equals(username) && field[4].equals(oldp) && newp.equals(cp)) {
                    field[4] = newp;
                    isupdated=true;
                }
                csvData.add(field);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        if(isupdated){
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            for (String[] field : csvData) {
            writer.write(String.join(",", field));
            writer.newLine();
        }
        } catch (IOException e) {
            e.printStackTrace();
        }
        updatePassword(newp);
    }
        return isupdated;
  }
    
    //kenot be mt
    public boolean emptypv() {
    if (oldpssw.getText().isEmpty()) {
        return false;
    }
    if (newpssw.getText().isEmpty()) {
        return false;
    } 
    if (confirmpssw.getText().isEmpty()) {
        return false;
    }
    return true;
    }
    
   public String getnewpssw(){
       return newpssw.getText();
   }
    
    public static void updatePassword(String newPassword) {
        String[] adminDetails = logintest.getuserDetails();
        if (adminDetails != null && adminDetails.length > 4) {
            adminDetails[4] = newPassword;
            logintest.setuserDetails(adminDetails); 
        }}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        oldpssw = new javax.swing.JTextField();
        newpssw = new javax.swing.JTextField();
        confirmpssw = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("New Password");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Confirm Password");

        oldpssw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpsswActionPerformed(evt);
            }
        });

        newpssw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpsswActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(oldpssw, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newpssw, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmpssw, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(oldpssw, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(newpssw, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(confirmpssw, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oldpsswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpsswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpsswActionPerformed

    private void newpsswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpsswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpsswActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmpssw;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField newpssw;
    private javax.swing.JTextField oldpssw;
    // End of variables declaration//GEN-END:variables
}
